# Generated by Django 5.2.4 on 2025-08-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_message_delete_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
